name: Legacii
favicon: null
layout_spectrum: 0.25946
title: 'Web design for the passionate entrepreneur '
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#0b0807'
    - '#3c3e43'
    - '#d2c2ba'
    - '#77818f'
    - '#575e68'
  brandStrength: 1
  lightness: 0.5
  saturation: 0.5
  rhythmicContrast: 0.5
purpose:
  - name: shares
    item: null
    url: null
