name: Legacii
favicon: null
layout_spectrum: 0.961148
typography_spectrum: 0.141891
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#B8B8C0'
    - '#000000'
    - '#788080'
    - '#000000'
    - '#000000'
  brandStrength: 0
  lightness: 0.375
  saturation: 0.5
  rhythmicContrast: 0.25
purpose:
  - name: shares
    item: null
    url: null
