analytics: {}
color:
  brandColors:
    - '#B8B8C0'
    - '#000000'
    - '#788080'
    - '#000000'
    - '#000000'
  brandStrength: 1
  lightness: 0.731418
  rhythmicContrast: 0.66554
  saturation: 0.5
cta: {}
layout_spectrum: 0.961148
name: Legacii
opengraph: {}
purpose:
  - name: shares
typography_spectrum: 0.141891
